version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongo:/data/db

  mongodb:
    image: mongo:8.0.1-noble
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    mysql:
      image: mysql:8.0.40-debian
      container_name: mysql
      hostname: mysql
      restart: always
      ports:
        - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
    neo4j:
      image: neo4j:5.24.2
      container_name: neo4j
      hostname: neo4j
      restart: always
      ports:
        - '7474:7474'
        - '7687:7687'